Repository RegioHelden/django-temporalio, pull requests merged in 2025-06, with the labels that each got.

#32 Update uv to 0.7.12
  Dockerfile
Labels: infrastucture

#35 Update reusable workflows
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  .sync.yml
Labels: infrastructure

#36 Update uv to 0.7.14
  Dockerfile
Labels: infrastucture

#37 Updates GitHub reusable workflows to 2.2.4
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#38 feat: add "heartbeat" context manager.
  README.md
  django_temporalio/utils.py
Labels: feature

#39 Release v1.3.0
  CHANGELOG.md
  version
Labels: skip-changelog

#40 Reset release to 1.2.0
  version
Labels: skip-changelog
