Repository RegioHelden/django-temporalio, pull requests merged in 2025-07, with the labels that each got.

#46 fix: pass proper update object
  django_temporalio/management/commands/sync_temporalio_schedules.py
Labels: bug

#47 Release v1.3.1
  CHANGELOG.md
  version
Labels: skip-changelog

#49 Release v1.4.0
  CHANGELOG.md
  version
Labels: skip-changelog

#52 Update uv to 0.8.2
  Dockerfile
Labels: infrastructure

#53 Update uv to 0.8.3
  Dockerfile
Labels: infrastucture
